### ISSUE TITLE
vue-cli hangs while creating new project

### ISSUE THREAD

**Issue by NekoGuy** [vuejs/vue-cli#1385]
### Version
3.0.0-beta.11

### Reproduction link
[]()

### Steps to reproduce
Use commands in console:

npm install -g @vue/cli

Then:

vue create application

### What is expected?
The project "application" was created

### What is actually happening?
After choosing parameters this text was showing in console for endless time :

Vue CLI v3.0.0-beta.12
-  Creating project in D:\projects.

And file "package.json" was created in folder "application" with content:

{
  "name": "application",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.12",
    "@vue/cli-plugin-typescript": "^3.0.0-beta.12",
    "@vue/cli-plugin-pwa": "^3.0.0-beta.12",
    "@vue/cli-plugin-unit-mocha": "^3.0.0-beta.12",
    "@vue/cli-plugin-e2e-cypress": "^3.0.0-beta.12",
    "@vue/cli-service": "^3.0.0-beta.12"
  }
}

---
npm version

{ npm: '6.1.0',
  ares: '1.14.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.29.0',
  node: '10.2.1',
  openssl: '1.1.0h',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.20.3',
  v8: '6.6.346.32-node.8',
  zlib: '1.2.11' }

vue --version

3.0.0-beta.12

Parameters which I chose:

default (babel, eslint)           -> hangs on creating
Manually select features     -> hangs on creating

I also tried to use "vue init webpack application" via @vue/cli-init and installed @vue/cli-service-global and it also hangs

All previous versions I removed

OS: Windows 10 x64

**Comment by NekoGuy** [comment]
All strings with "@" disappeared...

> npm install -g

Should be: npm install -g @**vue/cli**

> {
> "name": "application",
> "version": "0.1.0",
> "private": true,
> "devDependencies": {
> "": "^3.0.0-beta.12",
> "": "^3.0.0-beta.12",
> "": "^3.0.0-beta.12",
> "": "^3.0.0-beta.12",
> "": "^3.0.0-beta.12",
> "": "^3.0.0-beta.12"
> }
> }

Should be:

{ "name": "application", "version": "0.1.0", "private": true, "devDependencies": { "@**vue/cli-plugin-babel**": "^3.0.0-beta.12", "@**vue/cli-plugin-typescript**": "^3.0.0-beta.12", "@**vue/cli-plugin-pwa**": "^3.0.0-beta.12", "@**vue/cli-plugin-unit-mocha**": "^3.0.0-beta.12", "@**vue/cli-plugin-e2e-cypress**": "^3.0.0-beta.12", "@**vue/cli-service**": "^3.0.0-beta.12" } }

> I also tried to use "vue init webpack application" via and installed and it also hangs

Should be:

I also tried to use "vue init webpack application" via @**vue/cli-init** and installed @**vue/cli-service-global** and it also hangs

**Comment by yyx990803** [comment]
Are you behind a corporate proxy or anything like that?

**Comment by bblumberg** [comment]
I am getting the following when I do a vue create with the latest beta:

🚀  Invoking generators...
 ERROR  Error: Failed to resolve plugin: @vue/cli-service
Error: Failed to resolve plugin: @vue/cli-service
    at Creator.resolvePlugins (/Users/bruce/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:303:15)
    at Creator.create (/Users/bruce/.nvm/versions/node/v8.9.4/lib/node_modules/@vue/cli/lib/Creator.js:146:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by NekoGuy** [comment]
@yyx990803, I am not behind a corporate proxy. I've also tried to create a project via another internet provider
If You meant that vue-cli can't reach the download server I can try to ping it by myself

**Comment by Akryum** [comment]
This is unrelated and already fixed in #1397

**Comment by zmgalante** [comment]
I am getting the same error:

node: 'v10.3.0'
npm: '6.1.0',
yarn: '1.7.0'
Windows 10

Vue create is working fine, it creates everything, altough when i use vue ui it gives the same error above

C:\Users\Bold\front-end-base>vue ui
🚀  Starting GUI...
 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at Module.require (internal/modules/cjs/loader.js:644:11)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (C:\Users\Bold\AppData\Local\Yarn\config\global\node_modules\vue-cli-plugin-apollo\graphql-server\index.js:17:18)
    at module.exports (C:\Users\Bold\AppData\Local\Yarn\config\global\node_modules\vue-cli-plugin-apollo\graphql-server\index.js:39:28)
    at ui (C:\Users\Bold\AppData\Local\Yarn\config\global\node_modules\@vue\cli\lib\ui.js:41:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by nbnotabene** [comment]
Same problem here.

Work-around: bleeding **node version**
Same as https://github.com/vuejs/vue-cli/issues/1396

**Comment by NekoGuy** [comment]
In addition:

After executing "npm install -g @**vue/cli**" these messages appears:

![image](https://user-images.githubusercontent.com/10955129/40712887-728f81ea-6407-11e8-9e92-9664d23761a5.png)

So I've executed "npm install --save graphql@0.11.7" in "@**vue/cli**" folder:

![image](https://user-images.githubusercontent.com/10955129/40713037-c127777c-6407-11e8-9c39-4ae11dd266bb.png)

but more warnings appered

And creating project proccess still hangs

![image](https://user-images.githubusercontent.com/10955129/40713154-03df19c6-6408-11e8-9bc7-fa90220a8a6a.png)

P.S.: spinner before "Creating" is not rolling

**Comment by funnymania** [comment]
I too am having this problem using Vue CLI v3.0.0-beta.15. Identical warnings to what NekoGuy is experiencing. Same OS. 

If it helps, I have tried this using beta.10 and beta.15, which both hang.

**Comment by funnymania** [comment]
I fixed this using solution here: #1105 (comment) , except using beta.15.

Essentially, downgrading node to 8.11.2 worked for me.

**Comment by PeppeL-G** [comment]
I'm using Windows 10, and when I ran:

    npm i -g @vue/cli
    vue create my-project

Nothing happened (no folder created, no error message). Then I ran:

    npm i -g @vue/cli@v3.0.0-beta.15
    vue create my-project

And it worked (the folder `my-project` was created, and `npm run serve` worked as expected).

**Comment by yyx990803** [comment]
Should be fixed in beta.15 now.

**Comment by piboistudios** [comment]
Just wanted to note that for anyone still experiencing this problem, it is likely because you have Node.js v 10.3.0

**Comment by Olena-Stotska** [comment]
I found that it also hangs if  `~/.vuerc` file contains this:

```json
{
   "useTaobaoRegistry": true
}
```

you need to change this to : 

```json
{
   "useTaobaoRegistry": false
}
```

or just remote `.vuerc` file

**Comment by bigsee** [comment]
I had the same issue as @piboistudios and had to use nvm to download (and use) Node 8.12. Docs could probably make this clearer (unless I'm being totally blind).

**Comment by NathanWailes** [comment]
I had this issue after upgrading node and npm to the latest versions.  Re-installing vue-cli fixed it for me: `npm install -g @vue/cli`.

**Comment by montoyaedu** [comment]
We, @montoyaedu and @BeaChoq

 are experiencing the same problem with the latest version of node. In both, Mac OSX and Windows environments.

```bash
node --version
v12.4.0
npm --version
6.9.0
```

For some reason, it hangs at the second call of the function ask at:

```bash
/usr/local/lib/node_modules/\@vue/cli-init/node_modules/vue-cli/lib/generate.js
```

```javascript
/**
 * Create a middleware for asking questions.
 *
 * @param {Object} prompts
 * @return {Function}
 */

function askQuestions (prompts) {
  return (files, metalsmith, done) => {
    ask(prompts, metalsmith.metadata(), done)
  }
}
```

The method "ask" can be found at:

```
/usr/local/lib/node_modules/\@vue/cli-init/node_modules/vue-cli/lib/ask.js
```

We didn't have yet time to investigate, but as a workaround, we return and call the callback method "done" ate the very beginning.

```javascript
function prompt (data, key, prompt, done) {
 35     return done() 
 36   // skip prompts whose when condition is not met
 37   if (prompt.when && !evaluate(prompt.when, data)) {
 38     return done()
 39   }
```

**Comment by burzum** [comment]
Same issue here, Windows 10.

```
λ npm -v       
6.10.3         
λ node -v
v12.8.0
```

**Comment by ethan-deng** [comment]
I also see this issue with vue cli 4.0.5. I didn't see the issue with 4.0.1

**Comment by TraceyCanter** [comment]
Same issue here.  Finally got it working with vue ui.
