### ISSUE TITLE
failed to init from github enterprise (with a custom hostname) repository

### ISSUE THREAD

**Issue by ETiV** [vuejs/vue-cli#283]
## what happened

1. command I use

```
vue init -c github:git.company.com:User/webpack-simple
```

2. I expected the vue-cli **clones** the git repo from the specific URL to initiate a new project.

3. but after answering the questions, it returns the following error:

```
vue-cli · Local template "git.company.com:User/webpack-simple" not found.
```
----
## why it happens

I've checked the `bin/vue-init` file,
It seems like it's a conflict with the `local template test`, at here:
https://github.com/vuejs/vue-cli/blob/master/bin/vue-init#L93-L94

```
./ - for Linux CWD,
\w: - for Windows Disk Volume?
```

But it **DO CONFLICT** with the given argument,
because the [download-git-repo doc](https://www.npmjs.com/package/download-git-repo) says:

> ... you can also specify a custom host like gitlab:custom.com:owner/name. Feel free to submit an issue or pull request for additional host options.

----

In my case, I simply modified the file to bypass the local template testing:
```
#L94    if (!clone && /^[./]|(\w:)/.test(template)) {
```

Because I don't know how to exactly test the `local template path`(so many scenarios), so this is an issue instead of PR.

**Comment by likun7981** [comment]
you can change like this 
```js
/^\.{1,2}\/|^\w:|^\//.test(template) 
```

**Comment by ETiV** [comment]
@likun7981 
```
// it will be failed on
/^\.{1,2}\/|^\w:|^\//.test('templates/example')
```

**Comment by ETiV** [comment]
![layer](https://cloud.githubusercontent.com/assets/1926860/21630520/f219252a-d26c-11e6-8ca5-96eacbc9149d.png)

'templates/example' will be `github.com/templates/example`

I think it's better to add a switch to the command line arguments to specify whether to use a local template. Like:
```
vue init --local ${LOCAL_PATH}
```

**Comment by likun7981** [comment]
This is not wrong, `'templates/example'` is not a local path , it should return false

**Comment by likun7981** [comment]
These tests are all right
```js
var localPathRegx = /^\.{1,2}\/|^\w:|^\//  

localPathRegx.test('../')  //true
localPathRegx.test('./')  //true
localPathRegx.test('c:/') //true
localPathRegx.test('template/example')  //false
localPathRegx.test('github:git.company.com:User/webpack-simple')  //false
```

**Comment by zigomir** [comment]
Should be fixed now with #341.

**Comment by edwardnevermind** [comment]
When #341 should be released? I cloned the latest vue-cli repo  & installed it locally, but I still fail to init from the custom gitlab which I am using.  It gets stuck when ⠙ downloading template

**Comment by zigomir** [comment]
@edwardnevermind can't really say :/ but you can use `npm install -g vuejs/vue-cli` for now to install it directly from GitHub.

**Comment by winnieBear** [comment]
fail to init from the custom gitlab which I am using. It gets stuck when ⠙ downloading template
