### ISSUE TITLE
vue create npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex

### ISSUE THREAD

**Issue by danywalls** [vuejs/vue-cli#5183]
### Version
4.2.1

### Environment info
```
Windows 10
```

### Steps to reproduce
create a new project 

### What is expected?
Below error comes when creating a new project

### What is actually happening?
```
Vue CLI v4.1.2
✨  Creating project in C:\Users\dany\Desktop\hello2.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dany\AppData\Roaming\npm-cache\_logs\2020-02-12T12_57_45_506Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npmjs.org/
```

**Comment by sodatea** [comment]
It does exist on the registry https://registry.npmjs.org/error-ex

So it's likely an npm issue. Please run `npm cache verify` or `npm cache clean -f` and then try again.

**Comment by danywalls** [comment]
:( error continue 
`C:\Users\dany\Desktop> npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 6655 (398586221 bytes)
Content garbage-collected: 108 (4392309 bytes)
Index entries: 9922
Finished in 43.745s

C:\Users\dany\Desktop>npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.

C:\Users\dany\Desktop>vue create hello5


Vue CLI v4.1.2
┌─────────────────────────────────────────┐
│                                         │
│   New version available 4.1.2 → 4.2.2   │
│    Run npm i -g @vue/cli to update!     │
│                                         │
└─────────────────────────────────────────┘

? Please pick a preset: default-sass-jest-sass (router, node-sass, babel, eslint, unit-jest)


Vue CLI v4.1.2
✨  Creating project in C:\Users\dany\Desktop\hello5.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dany\AppData\Roaming\npm-cache\_logs\2020-02-12T13_21_04_535Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npmjs.org/`

**Comment by danywalls** [comment]
As a temporary fix, you can manually install node-error-ex after 'vue create myapp' failed.
```
cd myapp
npm i https://github.com/Qix-/node-error-ex
npm install
```

**Comment by alexbet** [comment]
I am getting the same error. Vue Cli v4.2.2

**Comment by sodatea** [comment]
It's an npm registry issue. https://status.npmjs.org/incidents/00tlqc4fzj14
Should have been fixed now.

**Comment by 7kemZmani** [comment]
I'm still seeing this issue when running `vue add vue-router`
```
📦  Installing vue-cli-plugin-vue-router...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/vue-cli-plugin-vue-router - Not found
npm ERR! 404 
npm ERR! 404  'vue-cli-plugin-vue-router@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abdulelah/.npm/_logs/2020-05-17T15_50_54_923Z-debug.log
 ERROR  command failed: npm install --loglevel error vue-cli-plugin-vue-router -D

```

**Comment by 7kemZmani** [comment]
I'm still seeing this issue when running `vue add vue-router`
```
📦  Installing vue-cli-plugin-vue-router...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/vue-cli-plugin-vue-router - Not found
npm ERR! 404 
npm ERR! 404  'vue-cli-plugin-vue-router@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-05-17T15_50_54_923Z-debug.log
 ERROR  command failed: npm install --loglevel error vue-cli-plugin-vue-router -D

```

**Comment by the-fanan** [comment]
I am still getting this error
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vue%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@vue/cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

**Comment by erman123456** [comment]
same, I also experienced the same thing, im using cli 4.5.8 and can't add plugins. can anyone help me?
