### ISSUE TITLE
Invoking generator: Received an unexpected value [object Undefined]

### ISSUE THREAD

**Issue by Tzahile** [vuejs/vue-cli#5380]
### Version
3.0.0-alpha.12

### Reproduction link
[https://github.com/Tzahile/vue3-plugin-installation](https://github.com/Tzahile/vue3-plugin-installation)

### Steps to reproduce
With vue-cli v4.3.1, `vue create new-project`.
(I don't know if it matters, but -) choose options as follows:
Please pick a preset: Manually select features
Check the features needed for your project: Babel, PWA, Router, Vuex, CSS Pre-processors, Linter
Use history mode for router? (Requires proper server setup for index fallback in production) No
Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with dart-sass)
Pick a linter / formatter config: Prettier
Pick additional lint features: Lint on save, Lint and fix on commit
Where do you prefer placing config for Babel, ESLint, etc.? In package.json

After settings a fresh new project, `vue add vue-next`

### What is expected?
plugin should be installed and set

### What is actually happening?
There is an error, caused just on post-installing the plugin:

TypeError: Received an unexpected value [object Undefined]

---
Full error:
```
Invoking generator for vue-cli-plugin-vue-next...
src\router\index.js
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:70:9)
    at core (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:45:5)
    at newCore (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:142:12)
    at module.exports (C:\Projects\five-in-row-with-vue3\node_modules\vue-cli-plugin-vue-next\generator\codemods\global-api\index.js:4:16)
    at newTransform (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-jscodeshift-adapter\src\jscodeshift-mode.js:9:14)
    at runCodemod (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\runCodemod.js:29:26)
    at C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\lib\GeneratorAPI.js:377:21
    at Generator.resolveFiles (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:268:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (C:\Users\tc02993\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:175:5)
```

When I tried to create a project with default presets, it worked.
Then I tried to add vue-router and got a different error:
```
 Invoking generator for @vue/cli-plugin-router...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
```

**Comment by posva** [comment]
Duplicate of https://github.com/vuejs/vue-cli-plugin-vue-next/issues/13

(couldn't transfer there)

**Comment by sodatea** [comment]
It's a path issue on Windows. Fixed in v0.1.2

**Comment by desian78** [comment]
It is not fixed.
Im on Linux (Ubuntu 20.04) have same issue at "vue add vuetify"

**Comment by MikeMitterer** [comment]
An I have the same problem on Mac

```bash
vue add vue-next
...

├─ vue-cli-plugin-vue-next@0.1.3
├─ vue-loader@16.0.0-beta.7
└─ webpack-node-externals@2.5.2
✨  Done in 44.96s.
✔  Successfully installed plugin: vue-cli-plugin-vue-next


🚀  Invoking generator for vue-cli-plugin-vue-next...
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (/Users/mikemitterer/.config/yarn/global/node_modules/jscodeshift/src/core.js:70:9)
    at core (/Users/mikemitterer/.config/yarn/global/node_modules/jscodeshift/src/core.js:45:5)
    at newCore (/Users/mikemitterer/.config/yarn/global/node_modules/jscodeshift/src/core.js:142:12)
    at module.exports (/Volumes/DevLocal/DevTypeScript/Templates/typescript-starter/node_modules/vue-cli-plugin-vue-next/generator/codemods/global-api/index.js:4:16)
    at newTransform (/Users/mikemitterer/.config/yarn/global/node_modules/vue-jscodeshift-adapter/src/jscodeshift-mode.js:9:14)
    at runCodemod (/Users/mikemitterer/.config/yarn/global/node_modules/@vue/cli/lib/util/runCodemod.js:29:26)
    at /Users/mikemitterer/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:377:21
    at Generator.resolveFiles (/Users/mikemitterer/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:268:13)
    at Generator.generate (/Users/mikemitterer/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:175:16)
    at runMicrotasks (<anonymous>)
```

**Comment by sodatea** [comment]
But vue-cli-plugin-vue-next is deprecated now. Use Vue CLI directly to create a Vue 3 project. Don't use `vue add vue-next`.

**Comment by MikeMitterer** [comment]
Yea - in my case the solution was: (this also shoed me some errors (one was that it could not find src/main.js (I have src/main.ts) but at least I could continue to upgrade from vue2 to vue3))

```bash
 yarn global add @vue/cli
vue add vue-next
```

**Comment by onurusluca** [comment]
I have it when tryin to install Vuetify.
