### ISSUE TITLE
New project with Vue 3 and typescript not working - SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by pranay-91** [vuejs/vue-cli#5861]
### Version
4.5.4

### Environment info
```
macos 10.14.4
node 14.5

```

### Steps to reproduce
Create a new project with Vue version 3, typescript option

### What is expected?
Build to work when `npm run serve`

### What is actually happening?
Build failed.

---
 @ ./src/App.vue?vue&type=template&id=7ba5bd90 1:0-379 1:0-379
 @ ./src/App.vue
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.0.149:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./src/views/About.vue?vue&type=template&id=039c5b43

Syntax Error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)

 @ ./src/views/About.vue?vue&type=template&id=039c5b43 1:0-396 1:0-396
 @ ./src/views/About.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.0.149:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./src/views/Home.vue?vue&type=template&id=fae5bece

Syntax Error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)

 @ ./src/views/Home.vue?vue&type=template&id=fae5bece 1:0-395 1:0-395
 @ ./src/views/Home.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.0.149:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

**Comment by sodatea** [comment]
Fixed in vue-loader 16.0.0-beta.7

**Comment by jirehnimes** [comment]
@sodatea What steps we need to do to fix this? Do we need to install vue-loader with that version? Re-install the vue-cli?

**Comment by m1aw** [comment]
This is not fixed, the current version of @vue/cli is still installing an older vue-loader, why is this issue close?

**Comment by sodatea** [comment]
But it does install the newer version. https://github.com/vuejs/vue-cli/blob/v4.5.7/packages/@vue/cli-service/package.json#L83

**Comment by Miguel-Bento-Github** [comment]
Any updates here?
If it has been fixed, which steps were done to reproduce the fix?

Thanks in advance.

**Comment by sodatea** [comment]
Update the dependencies.

**Comment by HTG-YT** [comment]
This issue is __still not fixed__ for me as of today:

Log:
```
 error  in ./src/components/dashboardComponents/ViewerComponent.vue?vue&type=template&id=b97faa74&bindings=undefined

Syntax Error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)


 @ ./src/components/dashboardComponents/ViewerComponent.vue?vue&type=template&id=b97faa74&bindings=undefined 1:0-380 1:0-380
 @ ./src/components/dashboardComponents/ViewerComponent.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/pages/dashboardPage/DashboardPage.vue?vue&type=script&lang=ts
 @ ./src/pages/dashboardPage/DashboardPage.vue?vue&type=script&lang=ts
 @ ./src/pages/dashboardPage/DashboardPage.vue
 @ ./src/pages/dashboardPage/entry.ts
 @ multi (webpack)-dev-server/client?http://<ipaddr>&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/pages/dashboardPage/entry.ts

 error  in ./src/components/dashboardComponents/tabsSubComponent/GuildConfigurationSubComponent.vue?vue&type=template&id=13421ccf&bindings=undefined

Syntax Error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)


 @ ./src/components/dashboardComponents/tabsSubComponent/GuildConfigurationSubComponent.vue?vue&type=template&id=13421ccf&bindings=undefined 1:0-410 1:0-410
 @ ./src/components/dashboardComponents/tabsSubComponent/GuildConfigurationSubComponent.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/dashboardComponents/tabsSubComponent/TabsSubComponent.vue?vue&type=script&lang=ts
 @ ./src/components/dashboardComponents/tabsSubComponent/TabsSubComponent.vue?vue&type=script&lang=ts
 @ ./src/components/dashboardComponents/tabsSubComponent/TabsSubComponent.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/dashboardComponents/ViewerComponent.vue?vue&type=script&lang=ts
 @ ./src/components/dashboardComponents/ViewerComponent.vue?vue&type=script&lang=ts
 @ ./src/components/dashboardComponents/ViewerComponent.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/pages/dashboardPage/DashboardPage.vue?vue&type=script&lang=ts
 @ ./src/pages/dashboardPage/DashboardPage.vue?vue&type=script&lang=ts
 @ ./src/pages/dashboardPage/DashboardPage.vue
 @ ./src/pages/dashboardPage/entry.ts
 @ multi (webpack)-dev-server/client?http://<ipaddr>&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/pages/dashboardPage/entry.ts
```

**Comment by HTG-YT** [comment]
Vue Version: 3.0.2
Vue Loader Version: 16.0.0-beta.8

**Comment by fangbinwei** [comment]
If you are using yarn, try
```json
  "resolutions": {
    "vue-loader-v16": "npm:vue-loader@^16.0.0-beta.8"
  }
```

check the version of `node_modules/vue-loader-v16` or `node_modules/@vue/cli-service/node_modules/vue-loader-v16`

the priority of `node_modules/@vue/cli-service/node_modules/vue-loader-v16` is higher
@HTG-YT

**Comment by HTG-YT** [comment]
I am **NOT** using yarn

**Comment by sodatea** [comment]
In a TS project? I'm gonna release a patch later today.

**Comment by HTG-YT** [comment]
Yes, it is a TypeScript project

**Comment by HTG-YT** [comment]
Looking forward to the patch 👍

**Comment by sodatea** [comment]
Fixed in beta.9

**Comment by HTG-YT** [comment]
Are the corresponding dependencies that use it have been updated?

**Comment by sodatea** [comment]
Just remove the lockfiles and reinstall the dependencies.

**Comment by HTG-YT** [comment]
Yup - it worked. Thank you

**Comment by HomyeeKing** [comment]
![image](https://user-images.githubusercontent.com/49113249/97872345-d995e280-1d50-11eb-9515-85eca0065bfe.png)


![image](https://user-images.githubusercontent.com/49113249/97872368-e1558700-1d50-11eb-8223-c0ef76efb718.png)

vue : ^3.0.3
![image](https://user-images.githubusercontent.com/49113249/97872422-f9c5a180-1d50-11eb-9e4f-b31b13063e90.png)
