### ISSUE TITLE
Failed at `npm run dev`

### ISSUE THREAD

**Issue by ajhsu** [vuejs/vue-cli#714]
For those people who encounter the following error messages:

```bash
$ vue init webpack-simple simple-example
$ cd simple-example
$ npm install
$ npm run dev

ajhsu-mbpr:simple-example ajhsu$ npm run dev

> simple-example@1.0.0 dev /Users/ajhsu/Git/vue/simple-example
> cross-env NODE_ENV=development webpack-dev-server --open --hot

webpack-dev-server 2.10.0
webpack 3.10.0
Usage: https://webpack.js.org/configuration/dev-server/

Config options:
  --config       Path to the config file
                         [string] [default: webpack.config.js or webpackfile.js]
  --config-name  Name of the config to use                              [string]

....

  --open-page   Open default browser with the specified page            [string]

Missing argument values: config, config-name, context, entry, module-bind, module-bind-post, module-bind-pre, output-path, output-filename, output-chunk-filename, output-source-map-filename, output-public-path, output-jsonp-function, output-library, output-library-target, records-input-path, records-output-path, records-path, define, target, watch-aggregate-timeout, devtool, resolve-alias, resolve-extensions, resolve-loader-alias, optimize-max-chunks, optimize-min-chunk-size, prefetch, provide, plugin, open-page
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-example@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --open --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-example@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajhsu/.npm/_logs/2018-01-09T09_28_10_300Z-debug.log
```

It seems caused by [a known issue](https://github.com/webpack/webpack-dev-server/issues/1259) on `webpack-dev-server@2.10.0`. While the generated vue project is requiring `webpack-dev-server@^2.9.1` which may install the broken version `2.10.0` that causes the error.

You can now temporary fix it by assigning the version of webpack-dev-server to 2.9.7 in your `package.json` like this: `"webpack-dev-server": "2.9.7"`.

**Comment by G-Veigar** [comment]
+1

**Comment by beer-on-ice** [comment]
++++++11111111111111111111111111

**Comment by roytime** [comment]
yarn remove webpack-dev-server
yarn add webpack-dev-server@2.9.1 --dev
yarn run dev  

OK!

**Comment by axtho** [comment]
Yeah, it is a webpack 2.9.10 issue. Downgrading this will help.

**Comment by ajhsu** [comment]
@axtho Actually [there has no `webpack-dev-server@2.9.10`](https://github.com/webpack/webpack-dev-server/releases), it's the problem of the `webpack-dev-server@2.10.0`. 😄

**Comment by axtho** [comment]
Right. That is correct.

**Comment by qingyunmeng042515** [comment]
yarn remove webpack-dev-server
yarn add webpack-dev-server@2.9.1 --dev
yarn run dev


亲测可以

**Comment by yyx990803** [comment]
2.10.1 should fix it too.

**Comment by pvfhv** [comment]
2.11.0无此Bug

**Comment by rgalaxy** [comment]
> 'cross-env' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! my-app@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --open --hot`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the my-app@1.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 

hi I still encounter this even after changing the webpack-dev-server to ^2.9.7

i just install vue-cli and this is my package json

> {
  "name": "my-app",
  "description": "A Vue.js project",
  "version": "1.0.0",
  "author": "",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },
  "dependencies": {
    "vue": "^2.5.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "file-loader": "^1.1.4",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "vue-loader": "^13.0.5",
    "vue-template-compiler": "^2.4.4",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.7"
  }
}


how do i fix this?

**Comment by ajhsu** [comment]
@rgalaxy That's not the problem related to this issue; 

It's simply because you haven't run `npm install` before `npm run dev` or `npm run build` yet.

**Comment by anson-GH** [comment]
change the config >index.js port: 8080 to other port eg, port: 8081

**Comment by slwzero** [comment]
npm uninstall webpack-dev-server
npm install webpack-dev-server@2.9.1 --dev
npm run serve

It works perfectly!

**Comment by tannhauserr** [comment]
@slwzero thanks, in 2019 and it's still failing

**Comment by MattHaydon** [comment]
> @slwzero thanks, in 2019 and it's still failing

Same. --unsafe-perm seemed. to fix.

**Comment by automatonatm** [comment]
npm remove webpack-dev-server
npm add webpack-dev-server@2.9.1 --dev
nmp run dev

this solves the whole problem

**Comment by toeurtenh** [comment]
thank you @automatonatm and @slwzero, it works for me

**Comment by 161710132** [comment]
help me

**Comment by salar80** [comment]
```
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install
```
`npm add webpack-dev-server@2.9.1 --dev`

**Comment by toeurtenh** [comment]
thank you it works

**Comment by vinnysihombing** [comment]
okee ^^

**Comment by coolapollo** [comment]
Unknown argument: mode
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forkify@1.0.0 dev: webpack --mode development
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forkify@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Apollo\AppData\Roaming\npm-cache_logs\2019-09-04T03_38_26_243Z-debug.log
PS C:\Users\Xxx\Desktop\9-forkify>

Still need help on this, above solutions didn’t help

**Comment by uroosehar1** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hellovue@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hellovue@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/uroo/.npm/_logs/2020-06-17T07_32_00_033Z-debug.log


cannot run node project suddenly

**Comment by FOWnglp** [comment]
> webpack-dev-server

我的还是不行

**Comment by sarwaras** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 03-webpack-ts@1.0.0 dev: `cross-env NODE_ENV=development webpack-dev-server --config build/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 03-webpack-ts@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rtt\AppData\Roaming\npm-cache\_logs\2022-05-19T02_56_16_701Z-debug.log
Waiting for the debugger to disconnect...

The above method still doesn't solve my problem~
