### ISSUE TITLE
Dev server throws error and is unable to start

### ISSUE THREAD

**Issue by roberthamel** [vuejs/vue-cli#859]
This also affects building the project too.

### Version
3.0.0-beta.1

### Reproduction link
reproducible through cli

### Steps to reproduce
```
Vue CLI v3.0.0-beta.1
? Please pick a preset: Manually select features
? Check the features needed for your project: TS, Router, Vuex, Unit, E2E
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Pick a unit testing solution: Jest
? Pick a E2E testing solution: Cypress
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
```

### What is expected?
Dev server to start

### What is actually happening?
```
[...]/node_modules/regex-not/index.js:62
    throw new Error('potentially unsafe regular expression: '   res);
    ^

Error: potentially unsafe regular expression: ^(?:(?!(?:[\[!* ?$^"'.\\/] )).) 
    at Function.toRegex.create (/Users/rh/Sites/vuecli3test/node_modules/regex-not/index.js:62:11)
    at createTextRegex (/Users/rh/Sites/vuecli3test/node_modules/nanomatch/lib/parsers.js:378:22)
    at Object.<anonymous> (/Users/rh/Sites/vuecli3test/node_modules/nanomatch/lib/parsers.js:14:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

**Comment by jonschlinkert** [comment]
This has been fixed:

- delete `node_modules`
- reinstall everything and make sure that npm or yarn don't use cached modules

**Comment by roberthamel** [comment]
I ran these commands:
- `rm -rf node_modules`
- `yarn cache clean`
- `yarn`
still the same problem when i run `yarn serve`

**Comment by jonschlinkert** [comment]
This was resolved, it is confirmed to be resolved. Make sure that all copies of `regex-not` are `1.0.2` (not `1.0.1`)

**Comment by roberthamel** [comment]
Thank you. The one step I missed was deleting the `yarn.lock` file before running `yarn` again. That fixed the issue.

**Comment by jonschlinkert** [comment]
> The one step I missed was deleting the yarn.lock file before running yarn again. That fixed the issue.

good suggestion.

**Comment by roberthamel** [comment]
Thank you again for the help. Much appreciated.
