### ISSUE TITLE
Allow for scoped plugins

### ISSUE THREAD

**Issue by corbinu** [vuejs/vue-cli#908]
### What problem does this feature solve?
It allows for plugins to be scoped. 

In my case I have my own eslint config so I was trying to publish a plugin for only my use. In this case `@corbinu/vue-cli-plugin-lint`. However none of the invoke commands were working. I believe that the regex for the hasPlugin function in PluginAPI.js simply needs to expanded slightly.

### What does the proposed API look like?
The api would look the same it would simply also work for plugins in a private npm scope.

**Comment by LinusBorg** [comment]
So this doesn't work?
```
vue invoke @corbinu/vue-cli-plugin-lint
```

because `hasplugin()` does also compare the id as-is:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/PluginAPI.js#L32

**Comment by yyx990803** [comment]
I think the runtime plugin auto-loading does not account for custom scoped packages at the moment.

**Comment by LinusBorg** [comment]
Ah, I see.

**Comment by yyx990803** [comment]
This has been addressed in latest `dev` branch and will be out in next beta release.

You will be able to do `vue add @corbinu/lint` or `vue invoke @corbinu/lint`, and the plugin should also be auto-loaded by the service.

**Comment by corbinu** [comment]
@yyx990803 Thanks trying it out now!

**Comment by corbinu** [comment]
@yyx990803 Sorry but this still doesn't need to be working. I pulled the dev branch and linked it in. 

`vue add @corbinu/lint` works great now however when I run `npm run lint` it still doesn't pick up on the service

```
npm run lint

> my-project@0.1.0 lint /Users/corbinu/Developer/git/my-project
> vue-cli-service lint

 ERROR  command "lint" does not exist.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 lint: `vue-cli-service lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/corbinu/.npm/_logs/2018-03-05T01_07_33_003Z-debug.log
```

**Comment by yyx990803** [comment]
@corbinu make sure your plugin is listed in `package.json`. Otherwise it won't be discovered.

**Comment by corbinu** [comment]
@yyx990803 `vue add @corbinu/lint` added it to the package.json automatically.

**Comment by yyx990803** [comment]
Probably a symlink issue. You'll need to file a separate issue after the next release.

**Comment by corbinu** [comment]
Ok thanks!

**Comment by johndpope** [comment]
(base) ➜  components git:(privacy) ✗ vue add @corbinu/lint

📦  Installing @corbinu/vue-cli-plugin-lint...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@corbinu%2fvue-cli-plugin-lint - Not found
npm ERR! 404
npm ERR! 404  '@corbinu/vue-cli-plugin-lint@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johndpope/.npm/_logs/2019-11-15T19_14_31_826Z-debug.log
 ERROR  command failed: npm install --loglevel error -D @corbinu/vue-cli-plugin-lint
```

0 info it worked if it ends with ok
1 verbose cli [ '/Users/johndpope/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/johndpope/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '-D',
1 verbose cli   '@corbinu/vue-cli-plugin-lint' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 766cb8bca5f0afa0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@corbinu%2fvue-cli-plugin-lint 1352ms
8 http fetch GET 404 https://registry.npmjs.org/@corbinu%2fvue-cli-plugin-lint 483ms
9 silly fetchPackageMetaData error for @corbinu/vue-cli-plugin-lint@latest 404 Not Found - GET https://registry.npmjs.org/@corbinu%2fvue-cli-plugin-lint - Not found
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 3283ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@corbinu%2fvue-cli-plugin-lint - Not found
12 verbose stack     at res.buffer.catch.then.body (/Users/johndpope/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @corbinu/vue-cli-plugin-lint@latest
15 verbose cwd /Users/johndpope/Documents/gitWorkspace/8secondz-contesthub/src/components
16 verbose Darwin 19.0.0
17 verbose argv "/Users/johndpope/.nvm/versions/node/v10.16.3/bin/node" "/Users/johndpope/.nvm/versions/node/v10.16.3/bin/npm" "install" "--loglevel" "error" "-D" "@corbinu/vue-cli-plugin-lint"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@corbinu%2fvue-cli-plugin-lint - Not found
22 error 404
23 error 404 '@corbinu/vue-cli-plugin-lint@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```
